const carSlots = (req, res) => {
  res.send(`
    <CarSlotInfoTrans>
    <CarsOwnedByPersona>
        <OwnedCarTrans>
            <CustomCar>
                <BaseCar>-951615808</BaseCar>
                <CarClassHash>1866825865</CarClassHash>
                <Id>119455</Id>
                <IsPreset>true</IsPreset>
                <Level>0</Level>
                <Name>silvias15</Name>
                <Paints>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>7</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>6</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>5</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>4</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>3</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>47885063</Group>
                        <Hue>496032624</Hue>
                        <Sat>0</Sat>
                        <Slot>2</Slot>
                        <Var>76</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032624</Hue>
                        <Sat>0</Sat>
                        <Slot>1</Slot>
                        <Var>76</Var>
                    </CustomPaintTrans>
                    <CustomPaintTrans>
                        <Group>42744494</Group>
                        <Hue>496032429</Hue>
                        <Sat>0</Sat>
                        <Slot>0</Slot>
                        <Var>0</Var>
                    </CustomPaintTrans>
                </Paints>
                <PerformanceParts>
                    <PerformancePartTrans>
                        <PerformancePartAttribHash>-9353752</PerformancePartAttribHash>
                    </PerformancePartTrans>
                    <PerformancePartTrans>
                        <PerformancePartAttribHash>-1772479284</PerformancePartAttribHash>
                    </PerformancePartTrans>
                    <PerformancePartTrans>
                        <PerformancePartAttribHash>-1037316126</PerformancePartAttribHash>
                    </PerformancePartTrans>
                    <PerformancePartTrans>
                        <PerformancePartAttribHash>-1257659725</PerformancePartAttribHash>
                    </PerformancePartTrans>
                    <PerformancePartTrans>
                        <PerformancePartAttribHash>-414914135</PerformancePartAttribHash>
                    </PerformancePartTrans>
                </PerformanceParts>
                <PhysicsProfileHash>-591225061</PhysicsProfileHash>
                <Rating>212</Rating>
                <ResalePrice>75000.0</ResalePrice>
                <RideHeightDrop>0.0</RideHeightDrop>
                <SkillModParts>
                    <SkillModPartTrans>
                        <IsFixed>false</IsFixed>
                        <SkillModPartAttribHash>1948827710</SkillModPartAttribHash>
                    </SkillModPartTrans>
                    <SkillModPartTrans>
                        <IsFixed>false</IsFixed>
                        <SkillModPartAttribHash>2004729337</SkillModPartAttribHash>
                    </SkillModPartTrans>
                    <SkillModPartTrans>
                        <IsFixed>false</IsFixed>
                        <SkillModPartAttribHash>-1544986384</SkillModPartAttribHash>
                    </SkillModPartTrans>
                </SkillModParts>
                <SkillModSlotCount>6</SkillModSlotCount>
                <Version>0</Version>
                <Vinyls/>
                <VisualParts>
                    <VisualPartTrans>
                        <PartHash>-1674761484</PartHash>
                        <SlotHash>-2126743923</SlotHash>
                    </VisualPartTrans>
                    <VisualPartTrans>
                        <PartHash>-256700190</PartHash>
                        <SlotHash>-1505530948</SlotHash>
                    </VisualPartTrans>
                    <VisualPartTrans>
                        <PartHash>-975922034</PartHash>
                        <SlotHash>-918850563</SlotHash>
                    </VisualPartTrans>
                    <VisualPartTrans>
                        <PartHash>161216366</PartHash>
                        <SlotHash>-966088147</SlotHash>
                    </VisualPartTrans>
                </VisualParts>
            </CustomCar>
            <Durability>100</Durability>
            <Heat>1.0</Heat>
            <Id>119455</Id>
            <OwnershipType>CustomizedCar</OwnershipType>
        </OwnedCarTrans>
    </CarsOwnedByPersona>
    <DefaultOwnedCarIndex>0</DefaultOwnedCarIndex>
    <ObtainableSlots>
        <ProductTrans>
            <BundleItems/>
            <CategoryId></CategoryId>
            <Currency>_NS</Currency>
            <Description>New car slot !!</Description>
            <DurationMinute>0</DurationMinute>
            <Hash>-1143680669</Hash>
            <Icon>128_cash</Icon>
            <Level>70</Level>
            <LongDescription>New car slot !</LongDescription>
            <Price>100.0</Price>
            <Priority>0</Priority>
            <ProductId>SRV-GARAGESLOT</ProductId>
            <SecondaryIcon></SecondaryIcon>
            <UseCount>1</UseCount>
            <VisualStyle></VisualStyle>
            <WebIcon></WebIcon>
            <WebLocation></WebLocation>
        </ProductTrans>
    </ObtainableSlots>
    <OwnedCarSlotsCount>40</OwnedCarSlotsCount>
</CarSlotInfoTrans>`);
};

module.exports = carSlots;
