module.exports = (req, res) => {
  res.send(`<LoginAnnouncementsDefinition>
    <Announcements>
        <LoginAnnouncementDefinition>
            <Context>NotApplicable</Context>
            <Id>1</Id>
            <ImageChecksum>-1</ImageChecksum>
            <ImageUrl>gIBGuRL.png</ImageUrl>
            <Target>http://www.world-evolved.ru</Target>
            <Type>ImageOnly</Type>
        </LoginAnnouncementDefinition>
        <LoginAnnouncementDefinition>
            <Context>NotApplicable</Context>
            <Id>2</Id>
            <ImageChecksum>-1</ImageChecksum>
            <ImageUrl>R9edIHb.png</ImageUrl>
            <Target>https://discord.gg/8cwZZqg </Target>
            <Type>ImageOnly</Type>
        </LoginAnnouncementDefinition>
        <LoginAnnouncementDefinition>
            <Context>NotApplicable</Context>
            <Id>3</Id>
            <ImageChecksum>-1</ImageChecksum>
            <ImageUrl>cPEcSmN.png</ImageUrl>
            <Target>https://discord.gg/8cwZZqg </Target>
            <Type>ImageOnly</Type>
        </LoginAnnouncementDefinition>
        <LoginAnnouncementDefinition>
            <Context>NotApplicable</Context>
            <Id>4</Id>
            <ImageChecksum>-1</ImageChecksum>
            <ImageUrl>JfFgga4.png</ImageUrl>
            <Target>https://vk.com/topic-98012462_38579134</Target>
            <Type>ExternalLink</Type>
        </LoginAnnouncementDefinition>
    </Announcements>
    <ImagesPath>http://i.imgur.com/</ImagesPath>
</LoginAnnouncementsDefinition>`);
};
