module.exports = (req, res) => {
    res.send(`<ArrayOfProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>952533007</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:B7A26CF0</ProductId>
        <ProductTitle>LAMBORGHINI</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-170970514</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:A9C647D5</ProductId>
        <ProductTitle>FORD</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>451662628</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:53C33DB0</ProductId>
        <ProductTitle>VOLKSWAGEN</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1186951366</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:FF730CD1</ProductId>
        <ProductTitle>DODGE</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-688005155</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>1100.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D6FDDFDD</ProductId>
        <ProductTitle>VUDU</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1077565943</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>800.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:403A59F7</ProductId>
        <ProductTitle>SOLO</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>678481367</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:A691F8DE</ProductId>
        <ProductTitle>Porsche </ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-2147002961</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:BFD68ED6</ProductId>
        <ProductTitle>CHEVROLET</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>776405284</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:36570C02</ProductId>
        <ProductTitle>RENNER</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1516934767</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:E366C630</ProductId>
        <ProductTitle>BUMPER STICKERS</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>938968009</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:7419DC51</ProductId>
        <ProductTitle>BMW</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>465216261</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:362ED2A1</ProductId>
        <ProductTitle>SNOWMAN</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-308850777</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D436F0A7</ProductId>
        <ProductTitle>SANTARINA</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-1313207994</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:4F1DFD0F</ProductId>
        <ProductTitle>AUDI</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1333978540</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:DADE3689</ProductId>
        <ProductTitle>TYLES</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1037191832</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:BEC9577E</ProductId>
        <ProductTitle>NISSAN PANEL VINYLS</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>732138705</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:ACCC8A93</ProductId>
        <ProductTitle>SPRING</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-930928800</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>500.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:C8832760</ProductId>
        <ProductTitle>SPECIAL</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>975375463</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>150.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:3A230C67</ProductId>
        <ProductTitle>TIOTAL</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-630819107</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>500.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:DA6676DD</ProductId>
        <ProductTitle>HATCH</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1630954120</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>400.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:61366288</ProductId>
        <ProductTitle>INKEE</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-1581360948</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>200.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:A1BE58CC</ProductId>
        <ProductTitle>VANDAL</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-1677520347</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>150.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:9C031225</ProductId>
        <ProductTitle>LINEAR</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-895494852</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:2664412A</ProductId>
        <ProductTitle>YEAR 2 ZL1 VINYLS</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1209488594</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>200.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:481754D2</ProductId>
        <ProductTitle>KEROSENE</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-728659978</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>1200.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D49187F6</ProductId>
        <ProductTitle>MASKIROVKA</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1636921707</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>500.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:6191716B</ProductId>
        <ProductTitle>NOMAD</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-653617830</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>1500.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D90A955A</ProductId>
        <ProductTitle>FLORCORE</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-1415837085</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:AB9C0A63</ProductId>
        <ProductTitle>MERIDIAN</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-689721571</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>800.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D6E3AF1D</ProductId>
        <ProductTitle>VISOR</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-427927574</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>150.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:E67E57EA</ProductId>
        <ProductTitle>CHICANE</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>1310612</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>999.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:0013FF94</ProductId>
        <ProductTitle>HOT PURSUIT</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-709890944</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>400.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:D5AFEC80</ProductId>
        <ProductTitle>EIKON</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-2123538394</Hash>
        <Icon></Icon>
        <Level>0</Level>
        <Price>0.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:446CD393</ProductId>
        <ProductTitle>YEAR 2 VINYLS</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
    <ProductTrans>
        <Currency>_NS</Currency>
        <DurationMinute>0</DurationMinute>
        <Hash>-1405213586</Hash>
        <Icon></Icon>
        <Level>1</Level>
        <Price>800.0</Price>
        <Priority>0</Priority>
        <ProductId>NFSW-NA:AC3E246E</ProductId>
        <ProductTitle>SHAPES</ProductTitle>
        <ProductType>CATEGORYTYPE</ProductType>
        <SecondaryIcon></SecondaryIcon>
        <UseCount>1</UseCount>
    </ProductTrans>
</ArrayOfProductTrans>`)
}